### ISSUE TITLE
Scrum Meeting 22-03-2023

### ISSUE THREAD

**Issue by chase-scott** [Favourolotu/Amazing-online-bookstore#25]
Features For Milestone 2:

1. Update the login page to collect and validate the username and password from the ones specified in the database for owners and users.
2. Adding the ability for a user to sort and filter books by attribute.
3. Changing the inventory implementation to follow a stock tracker format.

**Comment by chase-scott** [comment]
What I have done this week: Added full login functionality including encoded passwords.

What I will do next week: Add user registration, implement custom login page to handle this. Add css styling to whole web application. Add some SPA features to the owner page for graceful degradation.

Blockers: Limited documentation on Spring Security since many features have been deprecated, but was able to push through.

**Comment by Favourolotu** [comment]
What I have done this week: Updated the implementation of how an owner's inventory is managed i.e. how a book is added and how a quantity of a book is removed when the user makes a purchase. Updated the user-side to integrate the spring security. 

What I will do next week: Fix the bugs in the simulation of purchase logic, Add purchase recommendations for users.

Blockers: Updating the inventory stock number for books

**Comment by j-ctrl7** [comment]
What I have done this week: Implemented sorting options for the book list

what to do next week: add controller methods and integration tests for sort and filter

Blockers: unit tests for sorting feature, filter implementation to be completed
